'use client';

import "./globals.css";
import Header from "@/components/header/component";
import Footer from "@/components/footer/component";
import ContextProvider from "@/components/context-provider";
import { usePathname } from "next/navigation";
import { useEffect, useRef } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const mainRef = useRef();

  useEffect(() => {
    console.log('pathname', pathname);

    pathname === '/frontend/register' && (mainRef.current.style.marginTop = '0');
  }, []);

  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <Header/>

          <main ref={mainRef}>
            {children}
          </main>

          <Footer/>
            
        </ContextProvider>
      </body>
    </html>
  );
}
